# Generated by Django 5.2.18 on 2026-10-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
