# Generated by Django 5.2.18 on 2026-10-07 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_membership_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='advanced_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationrelation',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationrelation',
            name='responsibility',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organizationrelation',
            name='starts_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationrelation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='advanced_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RegistryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('term', 'Legislaturperiode'), ('committee', 'Gremium'), ('unit', 'Organisationseinheit'), ('function', 'Funktion'), ('person', 'Person ohne Konto'), ('faction', 'Fraktion'), ('room', 'Raum')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, max_length=2000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['kind', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('voting', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('substitutes_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mandate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='core.registryrecord')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faction_mandates', to='core.registryrecord')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='function_mandates', to='core.registryrecord')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_mandates', to='core.registryrecord')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_mandates', to='core.registryrecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='registryrecord',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='registry_period'),
        ),
        migrations.AddConstraint(
            model_name='mandate',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='mandate_period'),
        ),
        migrations.AddConstraint(
            model_name='mandate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('person__isnull', True), ('user__isnull', False)), models.Q(('person__isnull', False), ('user__isnull', True)), _connector='OR'), name='mandate_identity'),
        ),
    ]
