# Generated by Django 5.2.18 on 2026-10-07 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_advanced_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('organization_admin', 'Organisationsverwaltung'), ('reviewer', 'Fachbereichsleitung / Prüfung'), ('release', 'Freigabe'), ('clerk', 'Sitzungsdienst'), ('author', 'Sachbearbeitung'), ('chair', 'Vorsitz'), ('mayor', 'Bürgermeister'), ('local_mayor', 'Ortsbürgermeister'), ('member', 'Mandatsträger')], max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('organization_admin', 'Organisationsverwaltung'), ('reviewer', 'Fachbereichsleitung / Prüfung'), ('release', 'Freigabe'), ('clerk', 'Sitzungsdienst'), ('author', 'Sachbearbeitung'), ('chair', 'Vorsitz'), ('mayor', 'Bürgermeister'), ('local_mayor', 'Ortsbürgermeister'), ('member', 'Mandatsträger')], max_length=30),
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_kind', models.CharField(choices=[('organization', 'Körperschaft'), ('registry', 'Gremium / Stammdatensatz'), ('template', 'Vorlage'), ('unit', 'Organisationseinheit')], max_length=30)),
                ('resource_id', models.UUIDField()),
                ('actions', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=500)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
    ]
