# Generated by Django 5.2.18 on 2026-10-07 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_invitation_role_alter_membership_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeNonce',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeState',
            fields=[
                ('channel', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('received_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('kind', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='exchange_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExchangePolicy',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.organization')),
                ('protected_enabled', models.BooleanField(default=False)),
                ('public_enabled', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('resource_id', models.UUIDField()),
                ('resource_kind', models.CharField(default='registry', max_length=20)),
                ('base_version', models.PositiveIntegerField()),
                ('actor_id', models.PositiveBigIntegerField()),
                ('content', models.TextField(max_length=100000)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('revision', models.PositiveBigIntegerField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'revision'), name='unique_exchange_revision')],
            },
        ),
    ]
