# Generated by Django 5.2.18 on 2026-10-07 17:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exchangenonce_exchangestate_publicrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('emailed_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=300)),
                ('markdown', models.TextField(max_length=100000)),
                ('public_markdown', models.TextField(blank=True, max_length=100000)),
                ('fields', models.JSONField(default=dict)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('classification', models.CharField(choices=[('internal', 'Verwaltungsintern'), ('committee', 'Gremienkreis'), ('restricted', 'Eingeschränkter Personenkreis'), ('public_planned', 'Öffentlich vorgesehen')], default='internal', max_length=20)),
                ('state', models.CharField(default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('number', models.CharField(blank=True, max_length=40)),
                ('number_year', models.PositiveIntegerField(null=True)),
                ('number_sequence', models.PositiveIntegerField(null=True)),
                ('published_version', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.registryrecord')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=1)),
                ('deciding', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('may_amend', models.BooleanField(default=False)),
                ('amendment', models.TextField(blank=True, max_length=100000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.registryrecord')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='core.template')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='attachments/%Y/%m')),
                ('digest', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('media_type', models.CharField(max_length=100)),
                ('public', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('removed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000)),
                ('version', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_tasks', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='core.template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateKind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fields', models.JSONField(default=list)),
                ('initial_markdown', models.TextField(blank=True, max_length=100000)),
                ('workflow', models.JSONField(default=list)),
                ('four_eyes', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.templatekind'),
        ),
        migrations.CreateModel(
            name='TemplateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='core.template')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backlinks', to='core.template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.membership')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='core.template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.template')),
            ],
        ),
        migrations.CreateModel(
            name='EditPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.template')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'user'), name='unique_edit_presence')],
            },
        ),
        migrations.AddConstraint(
            model_name='templatekind',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_template_kind'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('organization', 'number_year', 'number_sequence'), name='unique_template_number'),
        ),
        migrations.AddConstraint(
            model_name='templateparticipant',
            constraint=models.UniqueConstraint(fields=('template', 'membership'), name='unique_template_participant'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='unique_template_version'),
        ),
    ]
