# Generated by Django 5.2.18 on 2026-10-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification_template_consultation_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='template',
            name='number_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='number_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='published_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatekind',
            name='fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='templatekind',
            name='workflow',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
