# Generated by Django 5.2.18 on 2026-10-07 17:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_template_fields_alter_template_number_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDocument',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('title', models.CharField(max_length=300)),
                ('markdown', models.TextField()),
                ('number', models.CharField(blank=True, max_length=40)),
                ('version', models.PositiveIntegerField()),
                ('permissions', models.JSONField(default=dict)),
                ('attachments', models.JSONField(default=list)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=300)),
                ('markdown', models.TextField(max_length=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.template')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=30)),
                ('substitute', models.CharField(blank=True, max_length=30)),
                ('group', models.PositiveIntegerField()),
                ('state', models.CharField(default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(null=True)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.membership')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_steps', to='core.template')),
            ],
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'year'), name='unique_number_sequence')],
            },
        ),
    ]
