# Generated by Django 5.2.18 on 2026-10-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_externaldocument_publication_reviewstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicaAsset',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('digest', models.CharField(max_length=64)),
                ('data', models.BinaryField()),
                ('received_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='publicrecord',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='publicrecord',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
