# Generated by Django 5.2.18 on 2026-10-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_replicaasset_publicrecord_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotechange',
            name='context_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
