# Generated by Django 5.2.18 on 2026-10-07 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remotechange_context_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=300)),
                ('public_title', models.CharField(blank=True, max_length=300)),
                ('public', models.BooleanField(default=True)),
                ('markdown', models.TextField(blank=True, max_length=100000)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subitems', to='core.agendaitem')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.template')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('state', models.CharField(default='preparation', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('statutory_count', models.PositiveIntegerField(default=1)),
                ('invitation_days', models.PositiveIntegerField(default=4)),
                ('proposal_deadline', models.DateTimeField(blank=True, null=True)),
                ('release_deadline', models.DateTimeField(blank=True, null=True)),
                ('public_notice', models.TextField(blank=True, max_length=10000)),
                ('public_enabled', models.BooleanField(default=False)),
                ('leading_server', models.CharField(default='internal', max_length=20)),
                ('active_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.agendaitem')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chaired_meetings', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='core.registryrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_meetings', to='core.registryrecord')),
                ('scribe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scribed_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.meeting'),
        ),
        migrations.CreateModel(
            name='MeetingAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_version', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('correction', 'Berichtigung'), ('urgent', 'Dringlicher neuer Gegenstand'), ('attachment', 'Zusätzliche Unterlage'), ('remove', 'Gegenstand absetzen'), ('reschedule', 'Termin ändern')], max_length=30)),
                ('reason', models.CharField(max_length=1000)),
                ('data', models.JSONField()),
                ('state', models.CharField(default='pending', max_length=20)),
                ('decision_record', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.meeting')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_amendments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='core.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('delivered_at', models.DateTimeField(null=True)),
                ('seen_at', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.meetinginvitation')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('private', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.meeting')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('meeting', 'membership'), name='unique_meeting_guest')],
            },
        ),
        migrations.AddConstraint(
            model_name='meetinginvitation',
            constraint=models.UniqueConstraint(fields=('meeting', 'revision'), name='unique_meeting_invitation'),
        ),
        migrations.AddConstraint(
            model_name='invitationdelivery',
            constraint=models.UniqueConstraint(fields=('invitation', 'user'), name='unique_invitation_delivery'),
        ),
    ]
