# Generated by Django 5.2.18 on 2026-10-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_agendaitem_meeting_agendaitem_meeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='frozen_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='meeting',
            name='permission_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
