# Generated by Django 5.2.18 on 2026-10-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_agendaitem_frozen_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitationdelivery',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
