# Generated by Django 5.2.18 on 2026-10-07 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_invitationdelivery_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNote',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.agendaitem')),
                ('markdown', models.TextField(blank=True, max_length=100000)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MeetingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('digest', models.CharField(max_length=64)),
                ('context_id', models.UUIDField()),
                ('device', models.UUIDField()),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.agendaitem')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.meeting')),
            ],
            options={
                'ordering': ['version', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingLease',
            fields=[
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.meeting')),
                ('context_id', models.UUIDField()),
                ('device', models.UUIDField()),
                ('epoch', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('function', models.CharField(blank=True, max_length=200)),
                ('voting', models.BooleanField(default=False)),
                ('present', models.BooleanField(default=False)),
                ('mandate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mandate')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster', to='core.meeting')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.registryrecord')),
                ('substitutes_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.meetingparticipant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConflictOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('reason', models.CharField(max_length=1000)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.agendaitem')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.meetingparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant', models.CharField(max_length=200)),
                ('wording', models.TextField(max_length=100000)),
                ('kind', models.CharField(choices=[('substantive', 'Sachantrag'), ('amendment', 'Änderungsantrag'), ('procedure', 'Geschäftsordnungsantrag')], max_length=30)),
                ('position', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(default='pending', max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motions', to='core.agendaitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='unique_meeting_user'),
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.UniqueConstraint(fields=('meeting', 'person'), name='unique_meeting_person'),
        ),
        migrations.AddConstraint(
            model_name='conflictofinterest',
            constraint=models.UniqueConstraint(fields=('participant', 'item'), name='unique_item_conflict'),
        ),
    ]
