# Generated by Django 5.2.18 on 2026-10-07 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_itemnote_meeting_paused_meetingevent_meetinglease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wording', models.TextField(max_length=100000)),
                ('mode', models.CharField(choices=[('manual', 'Handzeichen / Papier'), ('named', 'Digitale namentliche Abstimmung'), ('secret', 'Geheime Papierwahl')], max_length=20)),
                ('rule', models.CharField(default='majority_cast', max_length=30)),
                ('options', models.JSONField(default=list)),
                ('electorate', models.JSONField(default=list)),
                ('state', models.CharField(default='open', max_length=20)),
                ('result', models.JSONField(default=dict)),
                ('opened_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.agendaitem')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='core.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wording', models.TextField(max_length=100000)),
                ('result', models.JSONField(default=dict)),
                ('chair_confirmation', models.CharField(max_length=1000)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('progress', models.TextField(blank=True, max_length=100000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_decisions', to=settings.AUTH_USER_MODEL)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.vote')),
            ],
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.meetingparticipant')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='core.vote')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vote', 'participant'), name='one_ballot_per_elector')],
            },
        ),
    ]
