# Generated by Django 5.2.18 on 2026-10-07 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_vote_decision_ballot'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='authority_base',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SessionReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_version', models.PositiveIntegerField()),
                ('bundle', models.JSONField(default=dict)),
                ('digest', models.CharField(max_length=64)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('context_id', models.UUIDField()),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='core.meeting')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_session_returns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
