# Generated by Django 5.2.18 on 2026-10-07 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_decision_result_alter_vote_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='core.decision')),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('result', 'Ergebnisprotokoll'), ('course', 'Verlaufsprotokoll'), ('verbatim', 'Wortprotokoll')], default='result', max_length=20)),
                ('markdown', models.TextField(blank=True, max_length=200000)),
                ('public_markdown', models.TextField(blank=True, max_length=200000)),
                ('state', models.CharField(default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_version', models.PositiveIntegerField(blank=True, null=True)),
                ('public_snapshot', models.JSONField(blank=True, default=dict)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='minutes', to='core.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MinutesVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('reason', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('correction_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.meeting')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.minutes')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('minutes', 'version'), name='unique_minutes_version')],
            },
        ),
    ]
