# Generated by Django 5.2.18 on 2026-10-07 21:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_decisionupdate_minutes_minutesversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('markdown', models.TextField(blank=True, max_length=100000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.membership')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.meeting')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'context', 'meeting'), name='unique_personal_meeting_note')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('resource_id', models.UUIDField()),
                ('favorite', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.membership')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'context', 'kind', 'resource_id'), name='unique_workspace_entry')],
            },
        ),
    ]
