# Generated by Django 5.2.18 on 2026-10-07 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_personalnote_workspaceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineReceipt',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('context_id', models.UUIDField()),
                ('digest', models.CharField(max_length=64)),
                ('resulting_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.meeting')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
