# Generated by Django 5.2.18 on 2026-10-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_normalize_journal_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrecord',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
