# Generated by Django 5.2.18 on 2026-10-08 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_publicrecord_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(unique=True)),
                ('title', models.CharField(default='Bürgerinformation', max_length=120)),
                ('introduction', models.CharField(blank=True, max_length=500)),
                ('color', models.CharField(default='#245846', max_length=7)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('organizations', models.JSONField(blank=True, default=list)),
                ('frame_origins', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
