# Generated by Django 5.2.18 on 2026-10-08 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_portalconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('function', models.CharField(blank=True, max_length=200)),
                ('faction', models.CharField(blank=True, max_length=200)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=300)),
                ('photo', models.TextField(blank=True)),
                ('public_fields', models.JSONField(blank=True, default=list)),
                ('published', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
