# Generated by Django 5.2.18 on 2026-10-08 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_personprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailCursor',
            fields=[
                ('mailbox', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('uidvalidity', models.PositiveBigIntegerField()),
                ('last_uid', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MailReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(max_length=64)),
                ('uidvalidity', models.PositiveBigIntegerField()),
                ('uid', models.PositiveBigIntegerField()),
                ('category', models.CharField(max_length=30)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('sender', models.CharField(blank=True, max_length=200)),
                ('preview', models.TextField(blank=True, max_length=4000)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mailbox', 'uidvalidity', 'uid'), name='unique_mail_receipt')],
            },
        ),
    ]
