# Generated by Django 5.2.18 on 2026-10-08 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_importbatch_invitationdispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='personprofile',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.personidentity'),
        ),
        migrations.CreateModel(
            name='SampleBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_ids', models.JSONField(default=list)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.membership')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_bundles', to='core.organization')),
            ],
        ),
    ]
