# Generated by Django 5.2.18 on 2026-10-08 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_profile_identities'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='email', max_length=20)),
                ('secret', models.TextField(blank=True)),
                ('pending_secret', models.TextField(blank=True)),
                ('pending_expires_at', models.DateTimeField(null=True)),
                ('last_counter', models.BigIntegerField(default=-1)),
                ('recovery_hashes', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
