# Generated by Django 5.2.18 on 2026-10-08 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_passkey_webauthnceremony'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_kind', models.CharField(max_length=20)),
                ('resource_id', models.UUIDField()),
                ('reason', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('state', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.membership')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
