# Generated by Django 5.2.18 on 2026-10-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_emergencyaccess_systemoperator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('emergency', 'Befristeter Notfallzugriff'), ('organization_admin', 'Organisationsverwaltung'), ('reviewer', 'Fachbereichsleitung / Prüfung'), ('release', 'Freigabe'), ('clerk', 'Sitzungsdienst'), ('author', 'Sachbearbeitung'), ('chair', 'Vorsitz'), ('mayor', 'Bürgermeister'), ('local_mayor', 'Ortsbürgermeister'), ('member', 'Mandatsträger')], max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('emergency', 'Befristeter Notfallzugriff'), ('organization_admin', 'Organisationsverwaltung'), ('reviewer', 'Fachbereichsleitung / Prüfung'), ('release', 'Freigabe'), ('clerk', 'Sitzungsdienst'), ('author', 'Sachbearbeitung'), ('chair', 'Vorsitz'), ('mayor', 'Bürgermeister'), ('local_mayor', 'Ortsbürgermeister'), ('member', 'Mandatsträger')], max_length=30),
        ),
    ]
