# Generated by Django 5.2.18 on 2026-10-08 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('context_id', models.UUIDField()),
                ('token_digest', models.CharField(max_length=64)),
                ('password_basis', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('state', models.CharField(default='pending', max_length=20)),
                ('reset_factor', models.BooleanField(default=False)),
                ('factor_reset_applied', models.BooleanField(default=False)),
                ('encrypted_token', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
