# Generated by Django 5.2.18 on 2026-10-08 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_recoveryticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLSPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('hostname', models.CharField(max_length=253)),
                ('mode', models.CharField(max_length=20)),
                ('proof', models.CharField(max_length=80)),
                ('expected_ips', models.JSONField(default=list)),
                ('contact', models.EmailField(blank=True, max_length=254)),
                ('encrypted_material', models.TextField(blank=True)),
                ('certificate_info', models.JSONField(default=dict)),
                ('dns_verified_at', models.DateTimeField(null=True)),
                ('state', models.CharField(default='prepared', max_length=20)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
