# Generated by Django 5.2.18 on 2026-10-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_tlsplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlsplan',
            name='apply_requested_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tlsplan',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
