# Generated by Django 5.2.18 on 2026-10-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_tlsplan_apply_requested_at_tlsplan_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalState',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
